### ISSUE TITLE
Question about gumbel_keys() function in sample_subsets.py 

### ISSUE THREAD

**Issue by xxkkrr** [ermongroup/subsets#6]
Hi! Thanks for sharing the code!

I got a quesiton about gumbel_keys() function: 
https://github.com/ermongroup/subsets/blob/094af7f92ed4b30dd45a6bbdfae275c76fa60122/subsets/sample_subsets.py#L16
According to Algorithm2 in paper, there is a minus sign before z. 
I'm not familiar with Gumbel-max Trick, did I miss something?

**Comment by jcSole** [comment]
I just came across the same. I think you are right, there should be a minus sign before z. I guess, in general, the code may still work since on average the Gumbels(0,1) will be 0. but still...

**Comment by sangmichaelxie** [comment]
thanks for the comments -- somehow missed this! this is a typo, should be fixed.
